---
- platform: mqtt
  name: Boiler room light switch bot battery
  state_topic: switchbotMQTT/bot/boiler_room_light_switch
  device_class: battery
  value_template: "{{ value_json.batt }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: Oven fan switch bot battery
  state_topic: switchbotMQTT/bot/oven_fan_switch
  device_class: battery
  value_template: "{{ value_json.batt }}"
  unit_of_measurement: "%"
