---
- id: spotify_play
  alias: Play spotify using nfc tags
  mode: single
  max_exceeded: silent
  variables:
    tags:
      glenn_branca_the_ascension:
        media_content_id: spotify:album:2cFixT6QIE4gzPjZS7sen7
      swans_the_seer:
        media_content_id: spotify:album:774XM9c4BAxkNqvu7Rea1E
      johnny_cash_at_folsom_prison:
        media_content_id: spotify:album:4TJIdlY9hGSSTO1kUs1neh
      boris_akuma_no_uta:
        media_content_id: spotify:album:00oVPPcp3eor9x6VG2hvhy
      boris_feedbacker:
        media_content_id: spotify:album:2Xbd3EI9auhlw5WOKnNX3H
      chai_punk:
        media_content_id: spotify:album:0SkwXqlaB16ENaYJaPUW7d
  trigger:
    platform: event
    event_type: tag_scanned
  condition:
    - "{{ trigger.event.data.tag_id in tags }}"

  action:
    - variables:
        media_content_id: "{{ tags[trigger.event.data.tag_id].media_content_id }}"

    - service: media_player.play_media
      data:
        entity_id: media_player.spotify_sharktamer
        media_content_id: "{{ media_content_id }}"
        media_content_type: album

    - delay: 2

- alias: Turn on led strip at sunrise
  id: 'led_strip_turn_on'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_on
    data:
      entity_id: light.10m_strip
      brightness_pct: 100

- alias: Set light strip brightness to 1% at 8:30pm
  id: 'light_strip_evening_brightness'
  trigger:
    - platform: time
      at: "20:30:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.10m_strip
        brightness_pct: 1

- alias: Turn light strip off at 10:30pm
  id: 'light_strip_night_off'
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.10m_strip

- alias: Turn on office light when it gets dark
  id: 'office_light_after_dark'

  trigger:
    - platform: numeric_state
      entity_id: sensor.office_light_sensor_brightness
      below: 200

  action:
    - service: switch.turn_on
      entity_id: switch.office_light_mss510x_main_channel

- alias: Turn on stairs bulbs when motion is detected
  id: 'stairs_bulbs_motion_turn_on'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
      to: 'on'

  condition:
    - condition: numeric_state
      entity_id: sensor.lumi_lumi_sensor_motion_aq2_illuminance
      below: 10

  action:
    - service: light.turn_on
      entity_id: light.stairs_bulbs
      data:
        brightness_pct: >
          {%- if now().strftime('%H') | int >=22 %}
            1
          {%- elif now().strftime('%H') | int < 6 %}
            1
          {%- elif now().strftime('%H') | int >= 6 %}
            100
          {%- endif %}

- alias: Turn off stairs bulbs when motion is no longer detected
  id: 'stairs_bulbs_motion_turn_off'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
      to: 'off'

  action:
    - service: light.turn_off
      entity_id: light.stairs_bulbs

- alias: Turn on not when living room door is opened
  mode: single

  trigger:
    - type: opened
      platform: device
      device_id: d77c2bb1203ea741dec3261f678efc1d
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
      domain: binary_sensor

  action:
    - service: switch.turn_on
      entity_id: switch.01188014fcf5c4aa6a0c_4

- alias: Turn off not when living room door is closed
  mode: single

  trigger:
    - type: not_opened
      platform: device
      device_id: d77c2bb1203ea741dec3261f678efc1d
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
      domain: binary_sensor

  action:
    - service: switch.turn_off
      entity_id: switch.01188014fcf5c4aa6a0c_4

- alias: Turn on office heating when in office
  mode: single

  trigger:
    - platform: state
      entity_id: sensor.wren_room_presence
      to: office
      for: "00:02:00"

  action:
    - service: climate.set_temperature
      data:
        temperature: 22
      entity_id: climate.office

    - service: climate.set_temperature
      data:
        temperature: 15
      entity_id: climate.living_room

- alias: Turn on house heating when not in office
  mode: single

  trigger:
    - platform: state
      entity_id: sensor.wren_room_presence
      from: office
      for: "00:02:00"

  action:
    - service: climate.set_temperature
      data:
        temperature: 15
      entity_id: climate.office

    - service: climate.set_temperature
      data:
        temperature: 22
      entity_id: climate.living_room
