---
homeassistant:
  name: Paddlepond Home Assistant
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  unit_system: metric
  time_zone: Europe/London
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      allow_bypass_login: true
  # customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
python_script:

frontend:
  themes: !include_dir_merge_named themes

lovelace: !include lovelace/config.yaml

calendar: !include component_config/calendar.yaml
plex: !include component_config/plex.yaml
spotify: !include component_config/spotify.yaml
spotcast: !include component_config/spotcast.yaml
vacuum: !include component_config/robovac.yaml
webostv: !include component_config/webostv.yaml

device_tracker:
  - platform: luci
    host: 192.168.0.1
    username: !secret luci_username
    password: !secret luci_password

automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automations/

script: !include_dir_merge_named scripts/

camera: !include cameras.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
timer: !include timers.yaml

input_boolean: !include inputs/booleans.yaml
input_select: !include inputs/select.yaml
input_number: !include inputs/numbers.yaml

rest_command: !include commands/rest.yaml
shell_command: !include commands/shell.yaml

light groups: !include groups/lights.yaml
group: !include groups/switches.yaml
