---
- platform: template
  sensors:
    sunrise_time:
      friendly_name: Sunrise time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-up'

    sunset_time:
      friendly_name: Sunset time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-down'

    dawn_time:
      friendly_name: Dawn time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dawn) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-up'

    dusk_time:
      friendly_name: Dusk time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dusk) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-down'

    shane_presence_formatted:
      friendly_name: "Shane's location"
      value_template: "{{ (expand('group.room_presence')|selectattr('state', 'eq', 'on')|join('/', attribute='attributes.friendly_name')) or 'Away' }}"
      icon_template: 'mdi:account'

    total_download_speed:
      friendly_name: Total download speed
      value_template: "{{ states('sensor.transmission_down_speed') + states('sensor.nzbget_speed') + states('sensor.pyload_speed') }}"
      icon_template: 'mdi:download'

    transmission_queue_size:
      friendly_name: Transmission queue size
      value_template: "{{ states('sensor.transmission_total_torrents')|int - states('sensor.transmission_completed_torrents')|int }}"
      icon_template: 'mdi:download'

- platform: time_date
  display_options:
    - 'time'

- platform: seventeentrack
  username: !secret 17track_username
  password: !secret 17track_password

- platform: mqtt
  name: Office curtain battery
  state_topic: switchbotMQTT/curtain/office_curtain
  device_class: battery
  value_template: "{{ value_json.batt }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: Bedroom curtains battery
  state_topic: switchbotMQTT/curtain/bedroom_curtains
  device_class: battery
  value_template: "{{ value_json.batt }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: Living room curtains battery
  state_topic: switchbotMQTT/curtain/living_room_curtains
  device_class: battery
  value_template: "{{ value_json.batt }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: Boiler room light switch bot battery
  state_topic: switchbotMQTT/bot/boiler_room_light_switch
  device_class: battery
  value_template: "{{ value_json.batt }}"
  unit_of_measurement: "%"

- platform: integration
  source: sensor.wigeon_plug_power
  name: wigeon total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.paddlepond_plug_power
  name: paddlepond total power
  unit_prefix: k
  round: 2

- platform: pyload
  name: pyload
  host: pyload.media.svc.cluster.local
  username: !secret pyload_username
  password: !secret pyload_password

- platform: integration
  source: sensor.tv_plug_power
  name: tv total power
  unit_prefix: k
  round: 2
