---
- platform: template
  sensors:
    battery_doorbell:
      friendly_name: Doorbell battery
      unit_of_measurement: '%'
      value_template: "{{ state_attr('camera.doorbell', '1101') }}"
      device_class: battery

    sunrise_time:
      friendly_name: Sunrise time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-up'

    sunset_time:
      friendly_name: Sunset time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-down'

    dawn_time:
      friendly_name: Dawn time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dawn) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-up'

    dusk_time:
      friendly_name: Dusk time
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dusk) | timestamp_custom(' %I:%M %p') | replace(' 0', '') }}"
      icon_template: 'mdi:weather-sunset-down'

    shane_room_formatted:
      friendly_name: "Shane's location"
      value_template: "{{ states('sensor.moto_g_6_room_presence')|replace('_', ' ')|capitalize }}"
      icon_template: 'mdi:account'
