---
- platform: template
  sensors:
    battery_doorbell:
      friendly_name: Doorbell battery
      unit_of_measurement: '%'
      value_template: "{{ state_attr('camera.doorbell', '1101') }}"
      device_class: battery
