---
- name: wigeon
  platform: wake_on_lan
  mac: '2C:FD:A1:BE:32:53'
  host: 192.168.1.1
  turn_off:
    service: shell_command.sleep_wigeon

- platform: template
  switches:
    tv:
      value_template: "{{ is_state('media_player.tv', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.tv

- platform: mqtt
  name: bathroom fan
  command_topic: homeassistant/switch/switchbot/f3:87:77:eb:02:4e/set
  state_topic: homeassistant/switch/switchbot/f3:87:77:eb:02:4e/state
  icon: mdi:fan
