---
views:
  - !include lovelace/views/switches.yaml
  - !include lovelace/views/heating.yaml
  - !include lovelace/views/people.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/batteries.yaml
  - !include lovelace/views/power.yaml
  - !include lovelace/views/plants.yaml
