---
- platform: integration
  source: sensor.wigeon_plug_power
  name: wigeon total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.paddlepond_plug_power
  name: paddlepond total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.tv_plug_power
  name: tv total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.dishwasher_plug_power
  name: dishwasher total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.washing_machine_plug_power
  name: washing machine total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.dryer_plug_power
  name: dryer total power
  unit_prefix: k
  round: 2
