---
- alias: Turn on stairs bulbs when motion is detected
  id: 'stairs_bulbs_motion_turn_on'
  mode: restart

  trigger:
    - platform: state
      entity_id: binary_sensor.stairs_motion_occupancy
      to: 'on'

  condition:
    - condition: numeric_state
      entity_id: sensor.stairs_motion_illuminance
      below: 10

  action:
    - service: light.turn_on
      entity_id: light.stairs_bulbs
      data:
        brightness_pct: >
          {%- if now().strftime('%H') | int >=22 %}
            1
          {%- elif now().strftime('%H') | int < 6 %}
            1
          {%- elif now().strftime('%H') | int >= 6 %}
            100
          {%- endif %}

    - delay: '5'

    - service: python_script.set_state
      data:
        entity_id: binary_sensor.stairs_motion_occupancy
        state: 'off'

    - delay: '10'

    - service: light.turn_off
      entity_id: light.stairs_bulbs
