---
- alias: Open curtains at sunrise
  id: curtains_open_sunrise
  mode: single

  trigger:
    platform: sun
    event: sunrise

  action:
    - service: cover.open_cover
      target:
        entity_id:
          - cover.office_curtain

- alias: Close curtains at sunset
  id: curtains_close_sunset

  trigger:
    platform: sun
    event: sunset

  action:
    - service: cover.close_cover
      target:
        entity_id:
          - cover.bedroom_curtains
          - cover.office_curtain
