---
- platform: group
  name: Stairs bulbs
  entities:
    - light.stairs_upstairs_bulb
    - light.stairs_downstairs_bulb

- platform: group
  name: WLED bedroom
  entities:
    - light.wled_bed
    - light.wled_bedroom_dresser
