---
- alias: guest mode
  description: Disable presence switching when guest mode switch is on
  mode: single

  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode

  action:
    - service: >
        {% if trigger.to_state.state == 'on' %}
          automation.turn_off
        {% else %}
          automation.turn_on
        {% endif %}
      entity_id:
        - automation.set_living_room_presence_when_door_is_opened
        - automation.set_kitchen_presence_when_door_is_opened
        - automation.unset_kitchen_presence_when_door_is_closed
        - automation.set_bedroom_presence_when_door_is_opened
        - automation.set_office_presence_when_door_is_opened
        - automation.set_bathroom_presence_when_door_is_opened
        - automation.set_garden_presence_when_door_is_opened
