---
- alias: office diffuser control
  description: Automation to control office diffuser
  mode: single

  trigger:
    - platform: state
      entity_id: input_boolean.office_diffuser

  action:
    - choose:
        - conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.office_diffuser_on
      default:
        - service: scene.turn_on
          target:
            entity_id: scene.office_diffuser_off
