---
blueprint:
  name: Presence daapd
  description: Turn on daapd speakers when presence changes
  domain: automation

  input:
    presence:
      name: Presence
      description: Presence boolean to watch
    speaker:
      name: Speaker
      description: Speaker to turn on
    after_available:
      name: After available
      description: List of speakers to prioritise if they are available
      default: []
    after_on:
      name: After on
      description: List of speakers to prioritise if they are on
      default: []

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input presence
  - platform: state
    entity_id: !input speaker
    from: unavailable
  - platform: state
    entity_id: !input after_available
  - platform: state
    entity_id: !input after_on

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input presence
            state: 'on'
          - condition: state
            entity_id: !input after_available
            state:
              - 'unavailable'
          - condition: state
            entity_id: !input after_on
            state:
              - 'unavailable'
              - 'off'
        sequence:
          - service: media_player.turn_on
            entity_id: !input speaker
    default:
      - service: media_player.turn_off
        entity_id: !input speaker
