---
- alias: Doorbell notification
  id: 'doorbell_notification'
  mode: single

  trigger:
    - platform: state
      entity_id: switch.momentary_doorbell_press
      from: 'off'
      to: 'on'

  action:
    - service: notify.wigeon
      data:
        title: Doorbell
        message: Someone is at the door
        target: doorbell.png
