---
- alias: Doorbell notification
  id: 'doorbell_notification'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_doorbell_pressed
      to: 'on'

  action:
    - service: rest_command.wigeon_notify
      data:
        summary: Doorbell
        body: Someone pressed the doorbell
        icon: doorbell.png

- alias: Doorbell motion detection notification
  id: 'doorbell_motion_notification'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_person_detected
      to: 'on'

  action:
    - service: rest_command.wigeon_notify
      data:
        summary: Doorbell
        body: Someone is at the door
        icon: doorbell.png
