---
- alias: Turn on office heating when in office
  mode: single

  trigger:
    - platform: state
      entity_id: sensor.wren_room_presence
      to: office
      for: "00:01:00"

  action:
    - service: climate.set_temperature
      data:
        temperature: 22
      entity_id: climate.office

    - service: climate.set_temperature
      data:
        temperature: 15
      entity_id: climate.living_room

- alias: Turn on house heating when not in office
  mode: single

  trigger:
    - platform: state
      entity_id: sensor.wren_room_presence
      from: office
      for: "00:01:00"

  action:
    - service: climate.set_temperature
      data:
        temperature: 15
      entity_id: climate.office

    - service: climate.set_temperature
      data:
        temperature: 22
      entity_id: climate.living_room

- alias: Turn off heating at night
  mode: single

  trigger:
    - platform: state
      entity_id: sensor.wren_room_presence
      to: bedroom
      for: "00:15:00"

  condition:
    - condition: time
      after: '21:00:00'
      before: '09:00:00'

  action:
    - service: climate.set_temperature
      data:
        temperature: 15
      entity_id: climate.office

    - service: climate.set_temperature
      data:
        temperature: 15
      entity_id: climate.living_room
