---
- alias: Turn on stairs bulbs when motion is detected
  id: 'stairs_bulbs_motion_turn_on'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
      to: 'on'

  condition:
    - condition: numeric_state
      entity_id: sensor.lumi_lumi_sensor_motion_aq2_illuminance
      below: 10

  action:
    - service: light.turn_on
      entity_id: light.stairs_bulbs
      data:
        brightness_pct: >
          {%- if now().strftime('%H') | int >=22 %}
            1
          {%- elif now().strftime('%H') | int < 6 %}
            1
          {%- elif now().strftime('%H') | int >= 6 %}
            100
          {%- endif %}

- alias: Turn off stairs bulbs when motion is no longer detected
  id: 'stairs_bulbs_motion_turn_off'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
      to: 'off'

  action:
    - service: light.turn_off
      entity_id: light.stairs_bulbs
