---
# start timer when tag is scanned
- id: nfc_timer_start
  alias: Start timers using nfc tags
  mode: single
  max_exceeded: silent
  variables:
    tags:
      washing_machine_timer: "timer.washing_machine"
      dryer_mixed_load_timer: "timer.dryer_mixed_load"
  trigger:
    platform: event
    event_type: tag_scanned
  condition:
    - "{{ trigger.event.data.tag_id in tags }}"

  action:
    - variables:
        timer_id: "{{ tags[trigger.event.data.tag_id] }}"

    - service: timer.start
      data:
        entity_id: "{{ timer_id }}"

# Notify when timer finishes
- alias: Timer finished
  id: timer_finished

  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.washing_machine

  action:
    - service: rest_command.wigeon_notify
      data:
        summary: Washing machine finished
        icon: washing-machine.png

    - service: notify.mobile_app_wren
      data:
        message: "Washing machine finished"
        data:
          vibrationPattern: "0, 1000, 100, 1000"

- alias: Dryer timer finished
  id: dryer_timer_finished

  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dryer_mixed_load

  action:
    - service: rest_command.wigeon_notify
      data:
        summary: Dryer finished
        icon: tumble-dryer.png

    - service: notify.mobile_app_wren
      data:
        message: "Dryer finished"
        data:
          vibrationPattern: "0, 1000, 100, 1000"
