---
- alias: diffuser_light_fixed
  description: Set diffuser light to fixed when turned on
  mode: single

  trigger:
    - platform: state
      entity_id: light.office_diffuser_light
      to: 'on'

  action:
    - service: scene.turn_on
      target:
        entity_id: scene.office_diffuser_light_fixed
